### ISSUE TITLE
Crash on AE2 caused by QS

### ISSUE THREAD

**Issue by SirOMGitsYOU** [gigabit101/QuantumStorage#229]
Any possibility of a legacy fix for 1.12.2 for this? as it crashes the entire server when chunk is loaded

[crash-2020-09-22_13.37.16-server.txt](https://github.com/gigabit101/QuantumStorage/files/5261940/crash-2020-09-22_13.37.16-server.txt)

**Comment by DrUltraLux** [comment]
Hey. I'm the poor guy who is behind causing the crash. 
I have a very simple setup with a QStorage multiblock with only a single AE2 storage bus hooked up to one of the multiblock IO ports. My AE2 network is also tiny.

It looks like it causes AE2 to crash the whole server because the multiblock isn't formed when reloading the chunk and it gets a null pointer trying to get the GridStorageCache etc. from the IO. 

It could be fixed by returning a dummy empty inventory to the AE2 bus if the block hasn't yet formed maybe?

**Comment by gigabit101** [comment]
Yeah, I will look into it when I have some free time

**Comment by gigabit101** [comment]
1.12.2 is no longer supported, Update to newer versions
