### ISSUE TITLE
Dupe glitch with Quantum Storage Unit + Cyclic Sack of Holding

### ISSUE THREAD

**Issue by Tiax** [gigabit101/QuantumStorage#41]
See http://webmshare.com/D3YKz

Not sure if a problem with Cyclic or Quantum Storage, so I'll report on both repos.

**Comment by modmuss50** [comment]
Ok, I think its an issue that can be fixed by either of us, either by us rewriting the block droping (It needs doing anyway) or by them black listing that block.

Im going to link their issue here so the other dev might be able to provide his input: https://github.com/PrinceOfAmber/Cyclic/issues/131

This will also cause the same issue with some of TechReborns blocks.

**Comment by Tiax** [comment]
Closing: was fixed in Cyclic.
