### ISSUE TITLE
Issue on KookyKraft Hermit Craft server

### ISSUE THREAD

**Issue by RayzoRayy** [gigabit101/QuantumStorage#61]
I am one of the Helper's on this server, and I am not sure if it is your mod which is causing the issue, or the other mod NotEnoughWands, but the issue is a dupe bug. When you use a moving wand on a QuantumStorage tank, it duplicates and you get one extra back. I can't really give you to much more info the person who found the bug submitted it as a ticket and I told him or her, that one of the mod devs needed to fix it. Only other thing I can give you is the Forge Version, and your mod version as well as the other mod's version if you'd like to try and replicate it.
Forge Version- 12.18.3.2185
NotEnoughWands- 1.10-1.4.0
QuantumStorage- 1.10.2-3.77

**Comment by zed-hex** [comment]
this bug is this mods side and not NotEnoughWands side (90% sure). 
the bug happens when an item in another mods try to pick up the block since their mod wants to do something with the item (like move it into your inventory or somthing like that) 
but this mod does not use generic code for handling how the block is broken since how the mod needs to save the data of what was in the block
this is not 100% accurate but its more or less why the bug happens

**Comment by RayzoRayy** [comment]
And there is no way to fix it?

**Comment by gigabit101** [comment]
I can fix it myside

**Comment by RayzoRayy** [comment]
Okay,, thank you. :)
